namespace Marine.MySQL.API.Enums
{
    public enum MySqlDataType
    {
        TinyInt,
        SmallInt,
        MediumInt,
        Int,
        BigInt,
        Float,
        Double,
        Decimal,
        Date,
        DateTime,
        Timestamp,
        Time,
        Year,
        Char,
        VarChar,
        Binary,
        Varbinary,
        TinyBlob,
        Blob,
        MediumBlob,
        LongBlob,
        TinyText,
        Text,
        MediumText,
        LongText,
        Enum,
        Set
    }
}
